force-app/main/default/objects/InventoryItem__c/InventoryItem__c.object-meta.xml
<CustomObject>
    <description>Inventory Representation of Products</description>
    <label>Inventory Item</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InventoryItem__c/fields/LocationName__c.field-meta.xml
<CustomField>
    <fullName>LocationName__c</fullName>
    <description>the name of the Location</description>
    <formula>Location__r.Name</formula>
    <inlineHelpText>the name of the Location</inlineHelpText>
    <label>Location Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/ItemReservation__c.object-meta.xml
<CustomObject>
    <description>Represent each item the is reserved in a rental</description>
    <label>Item Reservation</label>
    <nameField>
        <displayFormat>RIR-{00000000}</displayFormat>
        <label>Item Reservation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ItemReservation__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>The date the item reservation ends.</description>
    <inlineHelpText>The date the item reservation ends.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/InventoryItem__c.field-meta.xml
<CustomField>
    <fullName>InventoryItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Product from Inventory that is being reserved for the Rental.</description>
    <inlineHelpText>The Product from Inventory that is being reserved for the Rental.</inlineHelpText>
    <label>Inventory Item</label>
    <referenceTo>InventoryItem__c</referenceTo>
    <relationshipLabel>Item Reservations</relationshipLabel>
    <relationshipName>ItemReservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/LocationName__c.field-meta.xml
<CustomField>
    <fullName>LocationName__c</fullName>
    <description>Name of Inventory Location</description>
    <formula>InventoryItem__r.Location__r.Name</formula>
    <inlineHelpText>Name of Inventory Location</inlineHelpText>
    <label>Location Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The Number of items to reserve.</description>
    <inlineHelpText>The Number of items to reserve.</inlineHelpText>
    <label>Quantity</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/Rental__c.field-meta.xml
<CustomField>
    <fullName>Rental__c</fullName>
    <description>The Parent Rental for the Item Reservation.</description>
    <inlineHelpText>The Parent Rental for the Item Reservation.</inlineHelpText>
    <label>Rental</label>
    <referenceTo>Rental__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>The date the item reservation starts.</description>
    <inlineHelpText>The date the item reservation starts.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/TotalRental__c.field-meta.xml
<CustomField>
    <fullName>TotalRental__c</fullName>
    <description>Total Amount of the Rental</description>
    <formula>PerDayTotalRental__c * ( EndDate__c -  StartDate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Amount of the Rental</inlineHelpText>
    <label>Total Rental</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rental__c/Rental__c.object-meta.xml
<CustomObject>
    <description>Represents a Rental Reservation for a Customer</description>
    <label>Rental</label>
    <nameField>
        <displayFormat>RA-{0000000}</displayFormat>
        <label>Rental ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rentals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>The Date the Rental Ends</description>
    <inlineHelpText>The Date the Rental Ends</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Date the Rental Begins</description>
    <inlineHelpText>Date the Rental Begins</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Tentative&quot;</defaultValue>
    <description>The status of the Rental</description>
    <inlineHelpText>The status of the Rental</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RentalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/RentalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tentative</fullName>
        <default>true</default>
        <label>Tentative</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Delivered</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Fulfilled/Completed</fullName>
    </customValue>
    <description>Values for Rental Status</description>
    <masterLabel>Rental Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RentallInventoryService.cls
/**
 * @description         This class provides Apex logic in order to expose inventory logic
 * @group               Services
 */
public with sharing class RentallInventoryService {
    /**
     * This method will determine if the inventory item is available between
     * the dates passed in
     * @param   inventoryId     String - the id of the InventoryItem__c record
     * @return  boolean         if true, only include rentals that have not been completed/returned. false returns
     *                          all records regardless of rental status.
     */
    @AuraEnabled
    public static List<ItemReservation__c> obtainReservationLinesByInventoryId(String inventoryId, 
            Boolean excludeCompletedRentals) {
        List<ItemReservation__c> retList;
        Set<String> includedRentalStatusSet = new Set<String>{'Tenative','Confirmed','Delivered'};
        if(!excludeCompletedRentals){
            includedRentalStatusSet.add('Received');
            includedRentalStatusSet.add('Fulfilled/Completed');
        }
        try {
            if(String.isBlank(inventoryId)){
                throw new IllegalArgumentException('inventoryId is required for obtainReservationLinesByInventoryId.');
            }
            System.SObjectAccessDecision decision = Security.stripInaccessible(System.AccessType.READABLE, [
                SELECT Id, Name, InventoryItem__c, LocationName__c, StartDate__c, EndDate__c, Rental__c, TotalRental__c,
                    Quantity__c, Rental__r.Status__c
                FROM ItemReservation__c
                WHERE Rental__r.Status__c IN :includedRentalStatusSet
            ],true);
            if(!decision.getRecords().isEmpty()){
                retList = decision.getRecords();
            }
        } catch(System.Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
        return retList;
    }
}