force-app/main/default/objects/InventoryItem__c/InventoryItem__c.object-meta.xml
<CustomObject>
    <description>Inventory Representation of Products</description>
    <label>Inventory Item</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InventoryItem__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>The Location of the Inventory Item</description>
    <inlineHelpText>The Location of the Inventory Item</inlineHelpText>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only relate inventory to RentAll Locations</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>RentAll Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>LocationInventory</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InventoryItem__c/fields/LocationName__c.field-meta.xml
<CustomField>
    <fullName>LocationName__c</fullName>
    <description>the name of the Location</description>
    <formula>Location__r.Name</formula>
    <inlineHelpText>the name of the Location</inlineHelpText>
    <label>Location Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InventoryItem__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <defaultValue>&quot;Auto Populated&quot;</defaultValue>
    <description>The Name of the Rental Product associated with the Inventory Item.  Automatically populated by System.</description>
    <inlineHelpText>The Name of the Rental Product associated with the Inventory Item.  Automatically populated by System.</inlineHelpText>
    <label>Product Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InventoryItem__c/fields/RentalProduct__c.field-meta.xml
<CustomField>
    <fullName>RentalProduct__c</fullName>
    <description>The Product of the Inventory Item</description>
    <inlineHelpText>The product of the inventory line.</inlineHelpText>
    <label>Rental Product</label>
    <referenceTo>RentalProduct__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/ItemReservation__c.object-meta.xml
<CustomObject>
    <description>Represent each item the is reserved in a rental</description>
    <label>Item Reservation</label>
    <nameField>
        <displayFormat>RIR-{00000000}</displayFormat>
        <label>Item Reservation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ItemReservation__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>The date the item reservation ends.</description>
    <inlineHelpText>The date the item reservation ends.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/InventoryItem__c.field-meta.xml
<CustomField>
    <fullName>InventoryItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Product from Inventory that is being reserved for the Rental.</description>
    <inlineHelpText>The Product from Inventory that is being reserved for the Rental.</inlineHelpText>
    <label>Inventory Item</label>
    <referenceTo>InventoryItem__c</referenceTo>
    <relationshipLabel>Item Reservations</relationshipLabel>
    <relationshipName>ItemReservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/LocationName__c.field-meta.xml
<CustomField>
    <fullName>LocationName__c</fullName>
    <description>Name of Inventory Location</description>
    <formula>InventoryItem__r.Location__r.Name</formula>
    <inlineHelpText>Name of Inventory Location</inlineHelpText>
    <label>Location Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/PerDayUnitRental__c.field-meta.xml
<CustomField>
    <fullName>PerDayUnitRental__c</fullName>
    <description>Rental Amount Per Day for each Unit</description>
    <inlineHelpText>Rental Amount Per Day for each Unit</inlineHelpText>
    <label>Per Day Unit Rental</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <description>Product Name of Reservation Item</description>
    <formula>InventoryItem__r.RentalProduct__r.Name</formula>
    <inlineHelpText>Product Name of Reservation Item</inlineHelpText>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The Number of items to reserve.</description>
    <inlineHelpText>The Number of items to reserve.</inlineHelpText>
    <label>Quantity</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/Rental__c.field-meta.xml
<CustomField>
    <fullName>Rental__c</fullName>
    <description>The Parent Rental for the Item Reservation.</description>
    <inlineHelpText>The Parent Rental for the Item Reservation.</inlineHelpText>
    <label>Rental</label>
    <referenceTo>Rental__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>The date the item reservation starts.</description>
    <inlineHelpText>The date the item reservation starts.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ItemReservation__c/fields/TotalRental__c.field-meta.xml
<CustomField>
    <fullName>TotalRental__c</fullName>
    <description>Total Amount of the Rental</description>
    <formula>PerDayTotalRental__c * ( EndDate__c -  StartDate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Amount of the Rental</inlineHelpText>
    <label>Total Rental</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rental__c/Rental__c.object-meta.xml
<CustomObject>
    <description>Represents a Rental Reservation for a Customer</description>
    <label>Rental</label>
    <nameField>
        <displayFormat>RA-{0000000}</displayFormat>
        <label>Rental ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rentals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>The Date the Rental Ends</description>
    <inlineHelpText>The Date the Rental Ends</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Date the Rental Begins</description>
    <inlineHelpText>Date the Rental Begins</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RentalProduct__c/RentalProduct__c.object-meta.xml
<CustomObject>
    <description>Basic information about a product that can be rented.</description>
    <label>Rental Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rental Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RentalProduct__c/fields/IsAvailable__c.field-meta.xml
<CustomField>
    <fullName>IsAvailable__c</fullName>
    <description>Formula field that determines if the product is available</description>
    <formula>AvailabilityStart__c &lt;= NOW() &amp;&amp; (ISBLANK(AvailabilityEnd__c) || AvailabilityEnd__c &gt; NOW())</formula>
    <inlineHelpText>AvailabilityEnd__c</inlineHelpText>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RentAllRentalInfoService.cls
/**
 * @description:        Provides Apex Logic for the Rental Object and the Rental Process.
 * @group:              Services
 */
public with sharing class RentAllRentalInfoService {
    @AuraEnabled(cacheable=true)
    public static List<ItemReservation__c> getItemReservationsByRentalId(String recordId){
        List<ItemReservation__c> retList = new List<ItemReservation__c>();
        try {
            if(String.isBlank(recordId)){
                throw new IllegalArgumentException('recordId is a required parameter');
            }
            SObjectAccessDecision decision = Security.stripInaccessible(AccessType.READABLE,[
                SELECT Id, EndDate__c, InventoryItem__c, Name, Quantity__c, Rental__c, StartDate__c,
                    ProductName__c, LocationName__c, PerDayUnitRental__c, TotalRental__c
                FROM ItemReservation__c WHERE Rental__c = :recordId
            ]);
            if(!decision.getRecords().isEmpty()){
                retList = (List<ItemReservation__c>)decision.getRecords();
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return retList;
    }
    @AuraEnabled(cacheable=true)
    public static Integer getItemReservationCountByRentalId(String recordId){
        Integer retVal;
        try {
            if(String.isBlank(recordId)){
                throw new IllegalArgumentException('recordId is a required parameter');
            }
            retVal = Database.countQuery('SELECT COUNT() FROM ItemReservation__c WHERE Rental__c = :recordId');
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return retVal;
    }
    @AuraEnabled(cacheable=true scope='global')
    public static List<LookupSearchResult> findInventoryByName(String searchTerm, List<String> selectedIds){
        List<LookupSearchResult> retList = new List<LookupSearchResult>();
        
        try {
            if(String.isBlank(searchTerm)){
                throw new IllegalArgumentException('searchTerm is a required parameter');
            }
            searchTerm = searchTerm + '*';
            String objectTypeName = Schema.InventoryItem__c.getSObjectType().getDescribe().getName();
            List<List<sObject>> soslResults = [FIND :searchTerm IN ALL FIELDS
                RETURNING InventoryItem__c(Id,Name,ProductName__c,Location__c,LocationName__c WHERE RentalProduct__r.IsAvailable__c = true)];
            if(!soslResults.isEmpty()){
                List<InventoryItem__c> inventoryList = (List<InventoryItem__c>)soslResults[0];
                for(InventoryItem__c item:inventoryList){
                    retList.add(new LookupSearchResult(item.Id,objectTypeName,'custom:custom6',item.ProductName__c,item.LocationName__c));
                }
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        return retList;
    }
    @AuraEnabled
    public static void deleteItemReservationsById(List<String> reservationIds){
        try {
            if(reservationIds == null || reservationIds.isEmpty()){
                throw new IllegalArgumentException('Reservation Record IDs must be provided');
            }
            List<ItemReservation__c> reservationRecords = [SELECT Id FROM ItemReservation__c WHERE Id IN :reservationIds];
            delete reservationRecords;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static void updateItemReservations(List<Map<String,String>> reservationUpdates){
        try {
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}